name: learn_live
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  url_launcher: ^6.2.1
  pdfx: ^2.9.0
  permission_handler: ^10.4.5
  flutter_dotenv: ^5.0.2
  jitsi_meet_wrapper: ^0.2.0+1
  path: ^1.8.3
  
  # Firebase packages for push notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Video player packages
  video_player: ^2.8.1
  chewie: ^1.7.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
